version:  '3.3'

services:

  nginx:
    image: nginx
    container_name: symfony_nginx
    volumes:
      - ./scripts/docker/dev/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    ports:
      - 80:80
    depends_on:
      - php
      - db

  php:
    build:
      context: ./scripts/docker/dev
      args:
        UID: $UID
        GID: $UID
    user: php:php
    dns:
      - 8.8.8.8
      - 8.8.4.4
    container_name: symfony_php
    volumes:
      - ./scripts/docker/dev/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./scripts/docker/dev/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - .:/var/www/html
    environment:
      XDEBUG_CONFIG: remote_host=172.17.0.1
      PHP_IDE_CONFIG: serverName=symfony

  db:
    image: postgres:10.1
    container_name: symfony_db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ./scripts/docker/dev/postgres/:/docker-entrypoint-initdb.d/
      - db:/var/lib/postgresql/data
      - ./var/dump:/var/dump

volumes:
  db:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/mnt/symfony/db'